version: "3.7"
services:
  app:
    image: reserva-dashboard-mkt
    build: .
    env_file: .env
    container_name: reserva-dashboard-mkt-app
    volumes:
      - ./:/app
    ports: ["80:80"]
    restart: "always"
